-- ============================================================================
-- vivagraph-ai : Supabase schema
--
-- Run this ONCE in the Supabase SQL Editor on a new project.
--
-- Why this file exists: the backend talks to Supabase through the PostgREST
-- client (supabase.table("...").insert(...)), which can only read and write
-- tables that already exist -- unlike the SQLAlchemy-based projects, it never
-- creates its own schema. Without these tables every write silently fails and
-- the app falls back to its local SQLite store.
--
-- Safe to re-run: every statement is idempotent.
-- ============================================================================

-- Users -----------------------------------------------------------------------
create table if not exists public.users (
    id          bigserial primary key,
    email       text unique not null,
    full_name   text,
    created_at  timestamptz not null default now()
);

-- Sessions --------------------------------------------------------------------
-- `id` is a UUID *string* generated by the app (uuid.uuid4()), not a DB default,
-- so it is text rather than uuid to accept exactly what the app sends.
create table if not exists public.sessions (
    id                text primary key,
    user_id           bigint references public.users(id) on delete cascade,
    topic             text,
    strictness_level  text,
    mode              text,
    final_score       numeric,
    feedback_summary  text,
    start_time        timestamptz not null default now()
);

-- /api/progress orders sessions by start_time descending.
create index if not exists sessions_user_start_idx
    on public.sessions (user_id, start_time desc);

-- Questions -------------------------------------------------------------------
create table if not exists public.questions (
    id              bigserial primary key,
    session_id      text references public.sessions(id) on delete cascade,
    question_text   text,
    question_order  integer,
    concept_focus   text,
    created_at      timestamptz not null default now()
);

create index if not exists questions_session_idx
    on public.questions (session_id);

-- Answers ---------------------------------------------------------------------
create table if not exists public.answers (
    id           bigserial primary key,
    question_id  bigint references public.questions(id) on delete cascade,
    transcript   text,
    audio_url    text,
    created_at   timestamptz not null default now()
);

create index if not exists answers_question_idx
    on public.answers (question_id);

-- Evaluations -----------------------------------------------------------------
create table if not exists public.evaluations (
    id                          bigserial primary key,
    answer_id                   bigint references public.answers(id) on delete cascade,
    feedback_text               text,
    concept_correctness_score   numeric,
    clarity_score               numeric,
    completeness_score          numeric,
    confidence_score_eval       numeric,
    follow_up_handling_score    numeric,
    created_at                  timestamptz not null default now()
);

create index if not exists evaluations_answer_idx
    on public.evaluations (answer_id);

-- Confidence metrics ----------------------------------------------------------
create table if not exists public.confidence_metrics (
    id                 bigserial primary key,
    answer_id          bigint references public.answers(id) on delete cascade,
    hesitation_count   integer,
    pause_duration_ms  integer,
    confidence_level   text,
    filler_word_count  integer,
    created_at         timestamptz not null default now()
);

create index if not exists confidence_metrics_answer_idx
    on public.confidence_metrics (answer_id);

-- Topic mastery ---------------------------------------------------------------
-- One row per (user, topic); the app reads mastery_level to adapt difficulty.
create table if not exists public.topic_mastery (
    id             bigserial primary key,
    user_id        bigint references public.users(id) on delete cascade,
    topic          text,
    mastery_level  integer default 0,
    updated_at     timestamptz not null default now(),
    unique (user_id, topic)
);

-- ============================================================================
-- Row Level Security
--
-- The backend is a trusted server (its key lives in Hugging Face Space
-- secrets), so the intended setup is:
--
--   SUPABASE_KEY = the **service_role** key
--
-- service_role bypasses RLS entirely, so leaving RLS enabled below keeps the
-- tables closed to anyone holding only the public anon key. That is the safe
-- combination and needs no policies.
--
-- If you would rather use the anon/publishable key, uncomment the policy block
-- instead -- but understand that it makes these tables world-readable and
-- world-writable by anyone who finds the key in your frontend bundle.
-- ============================================================================

alter table public.users              enable row level security;
alter table public.sessions           enable row level security;
alter table public.questions          enable row level security;
alter table public.answers            enable row level security;
alter table public.evaluations        enable row level security;
alter table public.confidence_metrics enable row level security;
alter table public.topic_mastery      enable row level security;

-- -- OPTIONAL: only if you are using the anon key rather than service_role.
-- create policy users_all              on public.users              for all using (true) with check (true);
-- create policy sessions_all           on public.sessions           for all using (true) with check (true);
-- create policy questions_all          on public.questions          for all using (true) with check (true);
-- create policy answers_all            on public.answers            for all using (true) with check (true);
-- create policy evaluations_all        on public.evaluations        for all using (true) with check (true);
-- create policy confidence_metrics_all on public.confidence_metrics for all using (true) with check (true);
-- create policy topic_mastery_all      on public.topic_mastery      for all using (true) with check (true);
